//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.3325.1758.g9aea513";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1758;
        public const string CEF_COMMIT_HASH = "9aea513c1cb66edba2c16518308dd98760ab18b3";
        
        public const int CHROME_VERSION_MAJOR = 65;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3325;
        public const int CHROME_VERSION_PATCH = 181;
        
        public const string CEF_API_HASH_UNIVERSAL = "4ee4ec86b45716685c08d2bfd898a2770f51d6eb";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "a3d9119fbd09bee8cac919e23c0e8c2826e5a340";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "7eca3e6e33556cbc835811f000a43c3e21aa336b";
        public const string CEF_API_HASH_PLATFORM_LINUX = "fd4c4a474b8da76a2172c83489ec3d490215459f";
    }
}
