//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.3282.1741.gcd94615";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1741;
        public const string CEF_COMMIT_HASH = "cd946151e1db8d5fd5d79400974403a76ab7b409";
        
        public const int CHROME_VERSION_MAJOR = 64;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3282;
        public const int CHROME_VERSION_PATCH = 119;
        
        public const string CEF_API_HASH_UNIVERSAL = "642ff98b5fe8952ba5f605660cfcb7dcbae78417";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "b881890cc9f9ab64382aee812d483a6873d8b1af";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "024ac1c9f578cd7c15d1b3b14a093d2c9e2d6e16";
        public const string CEF_API_HASH_PLATFORM_LINUX = "98cc1ee519c1c9cb1902b9d0d4a3273768658c9d";
    }
}
