//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.3239.1723.g071d1c1";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1723;
        public const string CEF_COMMIT_HASH = "071d1c16536ff012efd8f287823930c4b32e4f17";
        
        public const int CHROME_VERSION_MAJOR = 63;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3239;
        public const int CHROME_VERSION_PATCH = 132;
        
        public const string CEF_API_HASH_UNIVERSAL = "bcbe337b4de403c80689e8a5632b105cd51218c5";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "f0709e907eff18687c5b6fa4f6ec68e3683ab354";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "d0318bb377511c413efac7757489de0d2fb06bcf";
        public const string CEF_API_HASH_PLATFORM_LINUX = "13bcbe13c022cf9d2e7916638a09d60741e6ded2";
    }
}
