//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "96.0.18+gfe551e4+chromium-96.0.4664.110";
        public const int CEF_VERSION_MAJOR = 96;
        public const int CEF_COMMIT_NUMBER = 2468;
        public const string CEF_COMMIT_HASH = "fe551e4054895193c50598e64085e46a1eda77b0";
        
        public const int CHROME_VERSION_MAJOR = 96;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4664;
        public const int CHROME_VERSION_PATCH = 110;
        
        public const string CEF_API_HASH_UNIVERSAL = "21ac25aebdb49a8e8088c6fbee802b04fd07b501";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "1d81ccb5ba2f6d658abde2faeb490c8f7f6a60fe";
        public const string CEF_API_HASH_PLATFORM_MACOS = "d6bd1ab64a160962ee0306625da5dd2a0cae8b31";
        public const string CEF_API_HASH_PLATFORM_LINUX = "0b5227787444955a548b7544b2cdcda95a354506";
    }
}
