//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "101.0.15+gca159c5+chromium-101.0.4951.54";
        public const int CEF_VERSION_MAJOR = 101;
        public const int CEF_COMMIT_NUMBER = 2557;
        public const string CEF_COMMIT_HASH = "ca159c57bd1230a5f3483420c4af6580a4d929ef";
        
        public const int CHROME_VERSION_MAJOR = 101;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4951;
        public const int CHROME_VERSION_PATCH = 54;
        
        public const string CEF_API_HASH_UNIVERSAL = "34a42688778747c68f31e0194fea8323bc5388dc";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "c78306ad4768dc6c4ca1c376fa4c3799db8fd0eb";
        public const string CEF_API_HASH_PLATFORM_MACOS = "c25d8bb5b7118a8f50c84e8a2746b2a14d7193ef";
        public const string CEF_API_HASH_PLATFORM_LINUX = "742fc8a47e757e34a87c7c814fc884591d5e9f98";
    }
}
