//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "77.1.18+g8e8d602+chromium-77.0.3865.120";
        public const int CEF_VERSION_MAJOR = 77;
        public const int CEF_COMMIT_NUMBER = 2058;
        public const string CEF_COMMIT_HASH = "8e8d6022fae49f5ff6b6b55fee7556251b5ebcde";
        
        public const int CHROME_VERSION_MAJOR = 77;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3865;
        public const int CHROME_VERSION_PATCH = 120;
        
        public const string CEF_API_HASH_UNIVERSAL = "440be38b46f14493a9981a1d9282742a83b9070e";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "e5386095f03ffc204bdeacac7a13275918c66eb1";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "1c87ca78fce1bd15cd78f33f8f4e1763d616556a";
        public const string CEF_API_HASH_PLATFORM_LINUX = "0050dbeab6fe92dd6b954241224cb67c9d9ac23e";
    }
}
