//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "79.1.36+g90301bd+chromium-79.0.3945.130";
        public const int CEF_VERSION_MAJOR = 79;
        public const int CEF_COMMIT_NUMBER = 2130;
        public const string CEF_COMMIT_HASH = "90301bdb7fd0b32137c221f38e8785b3a8ad8aa4";
        
        public const int CHROME_VERSION_MAJOR = 79;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3945;
        public const int CHROME_VERSION_PATCH = 130;
        
        public const string CEF_API_HASH_UNIVERSAL = "3ad9591f7024619a1e2fd796c7ad51ae3a34abbb";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "3b8e38ae40c1a930227c6277c39dbc24081ccec1";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "4a77f1908fabccdb01a2d3bdbede5ca09fbaa394";
        public const string CEF_API_HASH_PLATFORM_LINUX = "434da6be7db70fd90c4265118ac47ace4073c6ae";
    }
}
