//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "3.3538.1852.gcb937fc";
        public const int CEF_VERSION_MAJOR = 3;
        public const int CEF_COMMIT_NUMBER = 1852;
        public const string CEF_COMMIT_HASH = "cb937fc9cd02a5b5f4d5aea2d880e05fbab621bf";
        
        public const int CHROME_VERSION_MAJOR = 70;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3538;
        public const int CHROME_VERSION_PATCH = 102;
        
        public const string CEF_API_HASH_UNIVERSAL = "040ce5036de742f2e20741ea315f8943acb52825";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "89b811362d1e7c4c7f63080451f8d2a29f3f123f";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "41afc46359f3ce0704aef51755b1f10fdf7091ed";
        public const string CEF_API_HASH_PLATFORM_LINUX = "1e06dc06555ed213fb88f06f5ac77a2bdc1a7198";
    }
}
